services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - 80:80
    volumes:
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
      - './:/var/www/app_cut'
    depends_on:
      - mysql_ilya
      - php_ilya

  php_ilya:
    container_name: php_ilya
    build:
      dockerfile: docker/php/Dockerfile
    volumes:
      - './:/var/www/app_cut'
    ports:
      - 8080:9000
      - 5174:5174

  mysql_ilya:
    container_name: mysql_ilya
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_data:/var/lib/mysql

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    ports:
#      - "9090:80"
#    environment:
#      PMA_HOST: mysql_ilya
#      PMA_PORT: 3306
#      PMA_USER: root
#      PMA_PASSWORD: root

volumes:
  db_data:
    driver: local
