
services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/app_cut
    depends_on:
      - mysql_ilya
      - php_ilya
  php_ilya:
    container_name: php_ilya
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./:/var/www/app_cut
    ports:
      - "8080:9000"
      - "5174:5174"
  mysql_ilya:
    container_name: mysql_ilya
    image: mysql:8.0
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db_data:/var/lib/mysql
  # vite:
  #   image: node:alpine
  #   working_dir: /app
  #   volumes:
  #     - ./:/app
  #   ports:
  #     - "5174:5174"


  # composer:
  #   container_name: composer
  #   build:
  #     context: dockerfiles
  #     dockerfile: composer.Dockerfile
  #   volumes:
  #     - db_data:/var/www/app_cut
  # artisan:
  #   container_name: artisan
  #   build:
  #     context: dockerfiles
  #     dockerfile: php.Dockerfile
  #   volumes:
  #     - ./:/var/www/app_cut
  #   entrypoint: [ "php", "/var/www/app_cut/artisan" ]

volumes:
  db_data:
