version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/app_cut
    depends_on:
      - mysql
      - php
  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./:/var/www/app_cut
    ports:
      - "8080:9000"
  mysql:
    image: mysql:8.0
    ports:
      - "3316:3306"
    env_file:
      - env/mysql.env
    volumes:
      - db_data:/var/lib/mysql
  vite:
    image: node:alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5174:5174"
    

  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - db_data:/var/www/app_cut
  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./:/var/www/app_cut
    entrypoint: [ "php", "/var/www/app_cut/artisan" ]

volumes:
  db_data:
